version: "3.9"
services:
  app:
    build:
      context: .
      target: builder
    image: michalzalecki/docker-compose-node
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start
